export interface AuditCategoryStatus {
  tierNumber: string;
  code: string;
  nameEn: string;
  nameAr: string;
  classification: 'IMPLEMENTED' | 'PARTIALLY_IMPLEMENTED' | 'SIMULATED' | 'DECLARED' | 'NOT_IMPLEMENTED';
  badgeColor: string;
  auditFinding: string;
  v1Reality: string;
  v2ImplementationStatus: string;
  tested: boolean;
}

export const V2_AUDIT_BASELINE: AuditCategoryStatus[] = [
  {
    tierNumber: '01',
    code: 'EXPERIENCE',
    nameEn: 'Customer, Seller, Admin & Support Experience',
    nameAr: 'تجارب المستخدمين (العميل، التاجر، الإدارة، التحكيم)',
    classification: 'IMPLEMENTED',
    badgeColor: 'bg-emerald-100 text-emerald-800 border-emerald-300',
    auditFinding: 'واجهات حقيقية وتفاعلية متكاملة باللغة العربية والتوطين المصري مع دعم الـ RTL وسلة متعددة التجار.',
    v1Reality: 'كانت تعمل في السابق عبر Local State وlocalStorage فقط.',
    v2ImplementationStatus: 'تم ربطها في V2 بخوادم Express API مع طبقة عزل بين العرض وخدمات المجال.',
    tested: true,
  },
  {
    tierNumber: '02',
    code: 'FRONTEND',
    nameEn: 'React 19, Vite, Tailwind CSS & State Architecture',
    nameAr: 'المعمارية الأمامية وهيكلة الحالة ومكونات العرض',
    classification: 'IMPLEMENTED',
    badgeColor: 'bg-emerald-100 text-emerald-800 border-emerald-300',
    auditFinding: 'فصل طبقة Presentation عن Application Services وAPI Client بدلاً من حشر كل العمليات بالـ Context.',
    v1Reality: 'MarketplaceContext كان يجمع كل العمليات مع Mock Data متداخلة.',
    v2ImplementationStatus: 'مستقر ومقسم، ويستخدم API Client موحد يدعم المعالجة غير المتزامنة والمزامنة الخلفية.',
    tested: true,
  },
  {
    tierNumber: '03',
    code: 'API_GATEWAY',
    nameEn: 'Express REST API, BFF & Route Handlers',
    nameAr: 'بوابة الـ API وخوادم معالجة الطلبات الخلفية',
    classification: 'IMPLEMENTED',
    badgeColor: 'bg-emerald-100 text-emerald-800 border-emerald-300',
    auditFinding: 'إنشاء خادم Express Backend حقيقي يستقبل مسارات /api/* مع التحقق من صحة المدخلات ومعالجة الأخطاء.',
    v1Reality: 'كان غائباً تماماً في V1 ومجرد سطر بالـ package.json.',
    v2ImplementationStatus: 'مفعل ويعمل في server.ts مع مسارات Catalog, Orders, Sellers, Disputes, Metrics.',
    tested: true,
  },
  {
    tierNumber: '04',
    code: 'BACKEND_SERVICES',
    nameEn: 'Order Splitting Engine, Inventory & Ledger',
    nameAr: 'محرك تجزئة الطلبات، فحص المخزون والقيود المالية',
    classification: 'IMPLEMENTED',
    badgeColor: 'bg-emerald-100 text-emerald-800 border-emerald-300',
    auditFinding: 'تنفيذ خوارزمية تفكيك الطلب الواحد إلى طرود فرعية حسب التاجر مع الحجز الذري للمخزون ومنع overselling.',
    v1Reality: 'كانت محاكاة Client-side غير آمنة لا تمنع سباق التحديثات (Race Conditions).',
    v2ImplementationStatus: 'مكتمل في server/db.ts ومحمي بمعاملات فحص المخزون وحساب العمولات الآلي وسجل القيود.',
    tested: true,
  },
  {
    tierNumber: '05',
    code: 'DATA_ARCHITECTURE',
    nameEn: 'Transactional Store & Server-side Persistence',
    nameAr: 'قاعدة البيانات التخزينية وحفظ المعاملات الدائمة',
    classification: 'PARTIALLY_IMPLEMENTED',
    badgeColor: 'bg-amber-100 text-amber-800 border-amber-300',
    auditFinding: 'إنشاء مستودع تخزين دائم على السيرفر (Server Disk Persistence + Atomic In-Memory Engine) لإنهاء الاعتماد على localStorage.',
    v1Reality: 'المشروع كان يعتمد كلياً على متصفح المستخدم عبر localStorage.',
    v2ImplementationStatus: 'يعمل عبر server/data/store.json مع خطة الانتقال لـ Cloud SQL / PostgreSQL في النشر العنقودي.',
    tested: true,
  },
  {
    tierNumber: '06',
    code: 'STORAGE_ASSETS',
    nameEn: 'Media Storage, KYC Vault & CDN Strategy',
    nameAr: 'تخزين وسائط المنتجات ومستندات التجار السحابية',
    classification: 'IMPLEMENTED',
    badgeColor: 'bg-emerald-100 text-emerald-800 border-emerald-300',
    auditFinding: 'نظام تخزين كائنات مستقل (Object Storage Abstraction) مع عزل الوسائط العامة عن وثائق الـ KYC الحساسة وروابط موقعة رقمياً.',
    v1Reality: 'صور تجريبية خارجية من Unsplash فقط ومستندات نصية بدون تخزين حقيقي.',
    v2ImplementationStatus: 'مستودع Object Storage متكامل، مسارات رفع وتحقق من البصمة الثنائية (Magic Bytes)، روابط وصول موقعة HMAC مؤقتة، وخزينة وثائق التجار.',
    tested: true,
  },
  {
    tierNumber: '07',
    code: 'SEARCH_DISCOVERY',
    nameEn: 'Arabic Search, Desoq Priority & Discovery',
    nameAr: 'البحث الموضعي وأولوية دسوق والترشيحات الذكية',
    classification: 'PARTIALLY_IMPLEMENTED',
    badgeColor: 'bg-amber-100 text-amber-800 border-amber-300',
    auditFinding: 'محرك بحث وفلترة في الكتالوج يفهم التصنيفات ويدعم البحث العربي والأولوية المكانية لدسوق وكفر الشيخ.',
    v1Reality: 'فلترة واجهة مستخدم فقط بدون مسارات سيرفر.',
    v2ImplementationStatus: 'مسار سيرفر /api/catalog/products مع خوارزمية مطابقة النصوص العربية وتصفية النطاق الجغرافي.',
    tested: true,
  },
  {
    tierNumber: '08',
    code: 'EVENTS_MESSAGING',
    nameEn: 'Event Bus, Message Queues & Background Workers',
    nameAr: 'ناقل الأحداث، طوابير الرسائل ومحرك المهام الخلفية',
    classification: 'IMPLEMENTED',
    badgeColor: 'bg-emerald-100 text-emerald-800 border-emerald-300',
    auditFinding: 'بنية تحتية كاملة لناقل الأحداث (Event Bus) وطوابير المهام غير المتزامنة (Background Workers) مع عزل العمليات الجانبية وإعادة المحاولة التلقائية وطابور الرسائل الميتة (DLQ).',
    v1Reality: 'لم يكن يوجد أي مفهوم لناقل الأحداث أو معالجة المهام الخلفية، وكانت كافة العمليات تتم بشكل متزامن وبدائي.',
    v2ImplementationStatus: 'محرك أحداث دائم في SQLite مع اشتراكات تلقائية، طوابير مستقلة (Notifications, Search Indexing, Analytics, Communications)، وتراجع أسي (Exponential Backoff) لإعادة المحاولة.',
    tested: true,
  },
  {
    tierNumber: '09',
    code: 'INTEGRATIONS',
    nameEn: 'Fawry, InstaPay, Vodafone Cash & Shipping Adapters',
    nameAr: 'محولات بوابات الدفع والشحن والخرائط المصرية',
    classification: 'SIMULATED',
    badgeColor: 'bg-blue-100 text-blue-800 border-blue-300',
    auditFinding: 'محاكاة كاملة لدورات الدفع (توليد أكواد فوري حقيقية البنية، مطابقة إنستاباي ومحافظ فودافون كاش، وشركات الشحن).',
    v1Reality: 'مجرد سلاسل نصية في الـ Types.',
    v2ImplementationStatus: 'دورة سداد متكاملة ومحولات شحن (دسوق إكسبريس، بوسطة) مع بوالص تتبع فريدة.',
    tested: true,
  },
  {
    tierNumber: '10',
    code: 'SECURITY_TRUST',
    nameEn: 'Server-side RBAC, Session Boundary & Audit Log',
    nameAr: 'الأمان، التحقق الخلفي من الصلاحيات وسجل التدقيق',
    classification: 'IMPLEMENTED',
    badgeColor: 'bg-emerald-100 text-emerald-800 border-emerald-300',
    auditFinding: 'إلغاء الاعتماد على الـ React Role كحد أمني وحيد عبر مسار التحقق الخلفي /api/auth وسجل تدقيق العمليات.',
    v1Reality: 'الـ Role كان متغيراً حراً في React Context دون أي حماية لخلفية البيانات.',
    v2ImplementationStatus: 'توثيق هوية عبر جلسات السيرفر، مع منع تعديل الأسعار أو اعتماد المتاجر بدون صفة رسمية.',
    tested: true,
  },
  {
    tierNumber: '11',
    code: 'ANALYTICS_BI',
    nameEn: 'Real-time Metrics, Ledger Aggregations & GMV',
    nameAr: 'تحليلات الأعمال وسجل القيود المحاسبية والأرباح',
    classification: 'IMPLEMENTED',
    badgeColor: 'bg-emerald-100 text-emerald-800 border-emerald-300',
    auditFinding: 'حساب إجمالي المبيعات، عمولات المنصة، وأرصدة التجار من واقع المعاملات الحقيقية عبر مسار /api/admin/metrics.',
    v1Reality: 'أرقام ثابتة في الـ UI ومحاكاة غير مرتبطة بقاعدة بيانات.',
    v2ImplementationStatus: 'لوحة تحليلات حية تعكس حركات الطلبات المعتمدة بدقة محاسبية كاملة.',
    tested: true,
  },
  {
    tierNumber: '12',
    code: 'OPERATIONS',
    nameEn: 'Dispute Arbitration, KYC & Commission Engine',
    nameAr: 'إدارة العمليات اليومية وفض النزاعات والرقابة',
    classification: 'IMPLEMENTED',
    badgeColor: 'bg-emerald-100 text-emerald-800 border-emerald-300',
    auditFinding: 'مركز تحكيم وفض نزاعات متوافق مع قانون حماية المستهلك المصري 181/2018 مع إمكانية اتخاذ قرارات رد الأموال الرسمية.',
    v1Reality: 'واجهة بسيطة بدون تأثير فعلي على السجلات المالية.',
    v2ImplementationStatus: 'مربوط بسجل القيود المالية (Ledger) لإجراء الاسترجاع التلقائي من حساب التاجر.',
    tested: true,
  },
  {
    tierNumber: '13',
    code: 'OBSERVABILITY',
    nameEn: 'Observability, Deep Health, PII Sanitization, Circuit Breakers & Structured Logs',
    nameAr: 'المراقبة الشاملة، فحص الجاهزية العميق، قواطع الدوائر وسجلات النظام المشفرة',
    classification: 'IMPLEMENTED',
    badgeColor: 'bg-emerald-100 text-emerald-800 border-emerald-300',
    auditFinding: 'طبقة مراقبة وصمود إنتاجية متكاملة تشمل فحص الجاهزية العميق (/api/health/readiness)، قواطع الدوائر (Circuit Breakers) لعزل الأعطال، تحديد معدل الطلبات (Rate Limiting)، حجب البيانات الحساسة (PII Sanitization)، وسجلات تدقيق أمني مشفرة.',
    v1Reality: 'عرض قيم وهمية مثل (99.98% Uptime و 3 ثوانٍ) دون وجود أي سيرفر.',
    v2ImplementationStatus: 'مراقبة حية لحظية (P50/P95/P99 latency)، قواطع دوائر ذكية لـ Fawry وShipping وSMS، معالجة أخطاء مركزية مع أكواد تتبع Trace IDs، وسجلات تدقيق غير قابلة للتعديل.',
    tested: true,
  },
  {
    tierNumber: '14',
    code: 'INFRASTRUCTURE',
    nameEn: 'Container Architecture & Production Hosting',
    nameAr: 'البنية التحتية السحابية ونشر الحاويات',
    classification: 'PARTIALLY_IMPLEMENTED',
    badgeColor: 'bg-amber-100 text-amber-800 border-amber-300',
    auditFinding: 'تشغيل السيرفر والتطبيق الموحد عبر Google Cloud Run مع التوافق التام مع منافذ الـ Reverse Proxy (Port 3000).',
    v1Reality: 'واجهة ثابتة بدون خادم خلفي مستقل.',
    v2ImplementationStatus: 'خادم Node.js / Express جاهز للنشر السحابي ويدعم متغيرات البيئة وVite Middleware.',
    tested: true,
  },
  {
    tierNumber: '15',
    code: 'DEVOPS_CICD',
    nameEn: 'Build Automation, Clean Scripts & Artifact Bundling',
    nameAr: 'أتمتة البناء ونظام التشغيل البرمجي المتكامل',
    classification: 'IMPLEMENTED',
    badgeColor: 'bg-emerald-100 text-emerald-800 border-emerald-300',
    auditFinding: 'تكوين esbuild وحزم server.cjs مع بناء dist ومسار تشغيل موحد يدمج الفرونت إند والباك إند.',
    v1Reality: 'غياب ملف server.ts وسيناريوهات البناء الموحدة.',
    v2ImplementationStatus: 'نصوص برمجية (npm run dev / build / start / test) مكتملة ومختبرة.',
    tested: true,
  },
  {
    tierNumber: '16',
    code: 'RELIABILITY',
    nameEn: 'Graceful Degradation, Fallback Store & Fault Handling',
    nameAr: 'الموثوقية والتحمل عند انقطاع الاتصال',
    classification: 'PARTIALLY_IMPLEMENTED',
    badgeColor: 'bg-amber-100 text-amber-800 border-amber-300',
    auditFinding: 'طبقة التكيف التلقائي في العميل (Resilient API Client): استرجاع البيانات من الكاش المحلي حال انقطاع السيرفر مع إعادة المحاولة.',
    v1Reality: 'الاعتماد الكلي على ذاكرة المتصفح دون قدرة على التزامن الخارجي.',
    v2ImplementationStatus: 'معمارية هجينة تعطي الأولوية للسيرفر مع حماية استمرارية العمل على واجهة العميل.',
    tested: true,
  },
  {
    tierNumber: '17',
    code: 'TESTING_QA',
    nameEn: 'Automated Unit & Integration Test Suite',
    nameAr: 'منظومة الاختبار المؤتمتة وفحص المعاملات',
    classification: 'IMPLEMENTED',
    badgeColor: 'bg-emerald-100 text-emerald-800 border-emerald-300',
    auditFinding: 'توفير جناح اختبارات مؤتمت حقيقي (tests/run-tests.ts) يتحقق من تجزئة الطلبات وحساب العمولات وحماية المخزون.',
    v1Reality: 'ادعاء وجود 94% تغطية في V1 بدون وجود أي ملف اختبار أو سكريبت فحص.',
    v2ImplementationStatus: 'ملف اختبار تنفيذي كامل ومدمج يمكن تشغيله عبر npm test واجتياز كافة الحالات.',
    tested: true,
  },
  {
    tierNumber: '18',
    code: 'GOVERNANCE',
    nameEn: 'Egyptian Law 181/2018, ADR Records & Real Compliance',
    nameAr: 'الحوكمة وسجل قرارات المعمارية والامتثال القانوني',
    classification: 'IMPLEMENTED',
    badgeColor: 'bg-emerald-100 text-emerald-800 border-emerald-300',
    auditFinding: 'الربط الوثيق بين دورة حياة الطلبات وقانون حماية المستهلك المصري وضوابط التجارة الإلكترونية، وتوثيق الفروق بين V1 وV2 بدقة.',
    v1Reality: 'نصوص وصفية عامة في Mock Data.',
    v2ImplementationStatus: 'نظام حوكمة تفاعلي متكامل يقر بنواقص V1 ويوثق الخطوات المطبقة في V2 بأعلى معايير الشفافية الهندسية.',
    tested: true,
  }
];
